heat_template_version: 2016-04-08
description: Ubuntu 16.04_64 Webserver.

parameters:
  key_name:
    type: string
    description: Name of Webserver SSH Key.
  subnet:
    type: string
    description: Name of Webserver Network.
  member_pool_id:
    type: string
    description: Pool ID that the server will be attached to be member of a loadbalancer.
  stack_id:
    type: string
    description: Heat stack id
  image_name:
    type: string
  flavor_name:
    type: string
  security_group:
    type: string
  lb_ip:
    type: string

resources:
  server:
    type: OS::Nova::Server
    properties:
      name: webserver
      image: {get_param: image_name}
      flavor: {get_param: flavor_name}
      key_name: {get_param: key_name}
      metadata: {"metering.stack": {get_param: stack_id}, "metering.scaletype": "webserver"}
      user_data: |
        #!/bin/sh
        host=$(hostname)
        sudo echo "127.0.0.1 $host" >> /etc/hosts
        sudo sed -i '/nameserver/c\nameserver 10.245.0.10' /etc/resolv.conf
      user_data_format: SOFTWARE_CONFIG
      networks:
        - subnet: {get_param: subnet}
      security_groups: [{get_param: security_group}]

  lb_member:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      address: {get_attr: [server, networks, private, 0]}
      admin_state_up: True
      pool: {get_param: member_pool_id}
      protocol_port: 80
      subnet: {get_param: subnet}

  lb_member2:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      address: {get_attr: [server, networks, private, 1]}
      admin_state_up: True
      pool: {get_param: member_pool_id}
      protocol_port: 80
      subnet: {get_param: subnet}

  config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
        - name: lb_ip
      config:
         get_file: conf_scripts/webserver.sh

  deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: HEAT_SIGNAL
      config:
        get_resource: config
      server:
        get_resource: server
      input_values:
        lb_ip: {get_param: lb_ip}
      actions:
        - CREATE